INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Abasolo', 'Centro', 1022);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Acuña', 'Norte', 163058);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Allende', 'Norte', 23056);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Arteaga', 'Sureste', 29578);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Candela', 'Centro', 1643);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Castaños', 'Centro', 29128);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Cuatro Ciénegas', 'Desierto', 12715);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Escobedo', 'Centro', 3047);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Francisco I. Madero', 'Laguna', 59035);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Frontera', 'Centro', 82409);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('General Cepeda', 'Sureste', 11898);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Guerrero', 'Norte', 1643);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Hidalgo', 'Norte', 1735);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Jiménez', 'Norte', 9502);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Juárez', 'Carbonífera', 1584);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Lamadrid', 'Centro', 1764);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Matamoros', 'Laguna', 118337);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Monclova', 'Centro', 237951);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Morelos', 'Norte', 7928);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Múzquiz', 'Carbonífera', 71627);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Nadadores', 'Centro', 6539);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Nava', 'Norte', 33129);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Ocampo', 'Desierto', 9642);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Parras', 'Sureste', 44472);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Piedras Negras', 'Norte', 176327);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Progreso', 'Carbonífera', 3239);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Ramos Arizpe', 'Sureste', 122243);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Sabinas', 'Carbonífera', 64811);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Sacramento', 'Centro', 2471);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Saltillo', 'Sureste', 879958);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('San Buenaventura', 'Centro', 24759);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('San Juan de Sabinas', 'Carbonífera', 42260);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('San Pedro', 'Laguna', 101041);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Sierra Mojada', 'Desierto', 6744);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Torreón', 'Laguna', 720848);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Viesca', 'Laguna', 20305);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Villa Unión', 'Norte', 6188);
INSERT INTO Municipios (Nombre, Region, Poblacion2020) VALUES ('Zaragoza', 'Norte', 13135);
